NewsPaper D3/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from rest_framework import routers
from news import views

router = routers.DefaultRouter()
router.register(r'author', views.AuthorViewset)
router.register(r'category', views.CategoryViewset)
router.register(r'post', views.PostViewset)
router.register(r'post_category', views.PostCatViewset)
router.register(r'comment', views.CommentViewest)


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # подключаем встроенные эндопинты для работы с локализацией
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('swagger-ui/', TemplateView.as_view(
       template_name='swagger-ui.html',
       extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
]

NewsPaper D3/news/urls.py
from django.urls import path
from .views import PostList, PostDetail, Search, NewsCreate, \
    ArticleCreate, NewsEdit, ArticleEdit, NewsDelete, ArticleDelete, subscriptions, Index
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),  # cache_page(60)(PostList.as_view())
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),  # cache_page(300)(PostDetail.as_view())
    path('search/', Search.as_view(), name='search'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('article/create/', ArticleCreate.as_view(), name='article_create'),
    path('news/<int:pk>/edit/', NewsEdit.as_view(), name='news_edit'),
    path('article/<int:pk>/edit/', ArticleEdit.as_view(), name='article_edit'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('article/<int:pk>/delete/', ArticleDelete.as_view(), name='article_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('hello/', Index.as_view(), name='hello'),
]

NewsPaper D3/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse
# D14
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy  # импортируем «ленивый» геттекст с подсказкой


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        posts_rating = Post.objects.filter(author=self).aggregate(pr=Coalesce(Sum('rating'), 0))['pr']
        comments_rating = Comment.objects.filter(user=self.user).aggregate(cr=Coalesce(Sum('rating'), 0))['cr']
        posts_comments_rating = Comment.objects.filter(post__author=self).aggregate(pcr=Coalesce(Sum('rating'), 0))['pcr']

        self.rating = posts_rating * 3 + comments_rating + posts_comments_rating
        self.save()

    def __str__(self):
        return f'{self.user.username}'


class Category(models.Model):
    name = models.CharField(max_length=80, unique=True, help_text=_('category name'))

    # def __str__(self):
    #     return f'{self.name}'

    def __str__(self):
        return self.name.title()


# абстрактный пример перевода в модели
# class MyModel(models.Model):
#     name = models.CharField(max_length=100)
#     kind = models.ForeignKey(
#         Category,
#         on_delete=models.CASCADE,
#         related_name='kinds',
#         verbose_name=pgettext_lazy('help text for MyModel model', 'This is the help text'),
#     )


class Post(models.Model):
    article = 'AR' or 'Статья'
    news = 'NE'
    CATEGORY_MATERIAL = [
        (article, 'Статья'),
        (news, 'Новость')
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category_post = models.CharField(max_length=2, choices=CATEGORY_MATERIAL, default=article)
    time_in = models.DateTimeField(auto_now_add=True)
    category_post_many = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:128] + '...'

    def __str__(self):
        return f'{self.title}: {self.text[:32]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    connectCategory = models.ForeignKey(Category, on_delete=models.CASCADE)
    connectPost = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.connectCategory}'


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

    def __str__(self):
        return f'{self.user.username}'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time_in = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper D3/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper D3/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Статья</h1>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

NewsPaper D3/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Привет! Новые статьи за последнюю неделю:</h2>
<ul>
    {% for post in new_posts %}
        <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

NewsPaper D3/templates/index.html
{% load i18n %} <!-- Загружаем теги с переводами, без этой строки ничего не будет работать -->
{% load tz %} <!-- не забываем загрузить тег для работы с часовыми поясами -->

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page title</title>
</head>
<body>
    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token
    для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        {% get_current_language as LANGUAGE_CODE %}
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>>
        <input type="submit" value="set">
    </form>

    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->

    {{ string }} <!-- Это уже знакомая нам переменная, просто засунули её в шаблон -->
    {% trans "Check out my new cool translation" %}! <!-- Переводим строку -->
</body>
</html>

NewsPaper D3/templates/input_output.html
{% load i18n %}
{% load tz %}

<html lang="en">
<head>
    <style>
        body {background-color: {% if current_time.hour >= 19 or current_time.hour <= 7 %} darkcyan {% else %} powderblue {% endif %};}
    </style>
</head>
<body>
    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token
    для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        {% get_current_language as LANGUAGE_CODE %}
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>>
        <input type="submit" value="set">
    </form>

    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ time_now|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->

</body>
</html>

NewsPaper D3/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper D3/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>Новость</h1>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

NewsPaper D3/templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token
    для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        {% get_current_language as LANGUAGE_CODE %}
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>>
        <input type="submit" value="set">
    </form>

<h1>{{ post.title }}</h1>
<h6>{{ post.time_in|date:'d.M.Y' }}</h6>
<hr>
{{ post.text|censor }}
{% endblock content %}

NewsPaper D3/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Новая <a href="{{ link }}">статья</a> в вашем разделе.</h2>
<p>{{ text }}</p>
</body>
</html>

NewsPaper D3/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %} <!-- не забываем загрузить тег для работы с часовыми поясами -->

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

<!-- {% include 'input_output.html' %} -->

{% block content %}
    {% trans "Найти" as search %}
    <!-- Если сейчас больше чем 19 или же меньше 7, то выводим тёмную тему, иначе выводим светлую -->
    <style>
        body {background-color: {% if current_time.hour >= 19 or current_time.hour <= 7 %} darkcyan {% else %} powderblue {% endif %};}
    </style>

    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token
    для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        {% get_current_language as LANGUAGE_CODE %}
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>>
        <input type="submit" value="set">
    </form>

    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ time_now|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->

    <h1>{% trans "Все публикации" %}</h1>
    <h3>{{ time_now|date:'d M Y' }}</h3>
    <h3> {{ posts|length }} </h3>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="{{ search }}" />
    </form>

    <hr>
    <!-- D5 -->
    {% if perms.news.add_post %}
    <a href="{% url 'news_create' %}">{% trans "Добавить новость" %}</a>
    {% endif %}
    {% if perms.news.add_post %}
    <a href="{% url 'article_create' %}">{% trans "Добавить статью" %}</a>
    {% endif %}

    {% if posts %}
        <table>
            <tr>
                <td>{% trans "Заголовок" %}</td>
                <td>{% trans "Дата публикации" %}</td>
                <td>{% trans "Содержание" %}</td>
                <!-- D5 -->
                {% if perms.news.change_post or perms.news.delete_post %}
                <td>{% trans "Действия" %}</td>
                {% endif %}

            </tr>

            {% for post in posts %}
            <tr>
                <td><a href="{% url 'post_detail' pk=post.id %}">{{ post.title }}</a></td>
                <td>{{ post.time_in|date:'d M Y h i s' }}</td>
                <td>{{ post.text|truncatechars:20|censor }}</td>
                <!-- D5 -->
                <td>
                    {% if post.category_post == "NE" %}
                        {% if perms.news.change_post %}
                            <a href="{% url 'news_edit' pk=post.id %}">{% trans "Изменить" %}</a>
                        {% endif %}
                        {% if perms.news.delete_post %}
                            <a href="{% url 'news_delete' post.id %}">{% trans "Удалить" %}</a>
                        {% endif %}
                    {% else %}
                        {% if perms.news.change_post %}
                            <a href="{% url 'article_edit' pk=post.id %}">{% trans "Изменить" %}</a>
                        {% endif %}
                        {% if perms.news.delete_post %}
                            <a href="{% url 'article_delete' post.id %}">{% trans "Удалить" %}</a>
                        {% endif %}
                    {% endif %}
                </td>

            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Публикаций нет</h2>
    {% endif %}

    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPaper D3/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load cache %}

{% block title %}
Search
{% endblock title %}

{% block content %}
    {% cache 30 search %}
        <h1>Поиск публикаций</h1>
        <h3>{{ time_now|date:'d M Y' }}</h3>
        <form action="" method="get">
            {{ filterset.form.as_p }}
            <input type="submit" value="Найти" />
        </form>
    {% endcache %}
    <hr>
    {% if posts %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Содержание</td>
            </tr>
            {% cache 30 list_fr %}
            {% for post in posts %}
            <tr>
                <td>{{ post.title }}</td>
                <td>{{ post.time_in|date:'d M Y h i s' }}</td>
                <td>{{ post.text|truncatechars:20|censor }}</td>
            </tr>
            {% endfor %}
            {% endcache %}
        </table>
    {% else %}
        <h2>Публикаций нет</h2>
    {% endif %}

    {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPaper D3/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

NewsPaper D3/templates/swagger-ui.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta
charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "//lms-cdn.skillfactory.ru/assets/courseware/v1/a084991b3a1596be3ed570c65c56393c/asset-v1:SkillFactory+FPW-2.0+27AUG2020+type@asset+block/openapi-schema.yml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>